---
title: "Examen parcial"
summary: " "
weight: 1
type: book
toc: false
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(collapse = TRUE)
```

## Instrucciones
  
El examen debe realizarse de manera individual y debe entregarse a más tardar las 13:35 am. en Teams. Solo en las preguntas 3 y 4 es necesario usar R o el software de su elección. Puede compactar su notación para ahorrar tiempo. Por ejemplo, puede escribir $y_i$ simplemente como $y$ y en vez de $\beta_1$ puede escribir simplemente $b1$. Por favor, **no comprima los archivos** en carpetas comprimidas. Al igual que las tareas, el examen debe contener:

Un primer documento de respuestas donde se incluyan las respuestas a las preguntas teóricas y conceptuales. Este documento puede ser redactado en Word o cualquier otro software, o si lo prefiere, a mano, pero deberá estar impreso en .pdf. En este documento también se deben incluir las respuestas a preguntas sobre conclusiones que se desprenden de las secciones prácticas. Por ejemplo, si una pregunta pide obtener la media de la variable x en cierta base de datos, entonces el documento de respuestas debe incluir la pregunta y respuesta correspondiente: “la media de la variable x es 32.6”.

Un segundo archivo deberá contener el código replicable usado para generar los resultados de la sección práctica. Los archivos de código se verificarán para comprobar su replicabilidad.

Recuerde que en Teams debe asegurarse de que los archivos se han subido correctamente.

**Al realizar este examen usted se compromete a no recibir ayuda de ninguna otra persona, por ningún medio. Ante la situación especial en que vivimos, entiendo que debemos ser flexibles en la forma en que esperamos que los alumnos aprendan y cómo tratamos de monitorear dicho aprendizaje. Al mismo tiempo, apelo a su madurez y honestidad intelectual. Recuerde que se aplicarán estrictamente los lineamientos generales del CIDE en términos de plagio y fraude.**


## Archivos

[ingresos_iv.csv](/examenes/ingresos_iv.csv)


## Pregunta 1

Considere una variable aleatoria $x$ que se distribuye de acuerdo a la función de densidad gamma, con parámetros $\alpha$ (forma) y $\lambda$ (tasa): $$ f(x | \alpha, \lambda) = \frac{1}{\Gamma(\alpha)}\lambda^{\alpha}x^{\alpha-1}e^{-\lambda x}$$ Se asume $\alpha>0$, $\lambda>0$ y $x_i>0$. La función $\Gamma(a)$ se define como $\Gamma(a)=(a-1)!$, aunque en este problema puede trabajar simplemente dejando la función indicada.

a. [5 puntos] Escriba la log verosimilitud de la observación $i$.

a. [5 puntos] Escriba la log verosimilitud del problema para la muestra de tamaño $N$.

a. [5 puntos] Obtenga las condiciones de primer orden para la maximización del problema de log verosimilitud. En el resto del problema, no necesita calcular explícitamente la derivada $\frac{d \ln (\Gamma(\alpha))}{d \alpha}$, basta con dejarla indicada donde corresponda.

a. [5 puntos] Usando la condición de primer orden $\frac{\partial\mathcal{L}}{\partial \lambda}=0$ derive una expresión para $\lambda$ en términos de $\alpha$ y las $x_i$.

a. [5 puntos] Sustituya la expresión anterior para $\lambda$ en términos de $\alpha$ y las $x_i$ en la condición de primer orden $\frac{\partial\mathcal{L}}{\partial \alpha}=0$ y obtenga una expresión que represente el problema de optimización que debe ser solucionado de manera numérica.

a. [5 puntos] Obtenga la matriz de información de Fisher.
 
# Pregunta 2

Construya un breve argumento para los siguientes dos puntos, ambos independientes entre sí. Puede auxiliarse o no de ecuaciones, aunque lo más importante son sus argumentos conceptuales.

a. [10 puntos] En un modelo de regresión lineal como sigue: $$y_i=a + X_i b + e_i$$ con $y_i$ continua y $K$ regresores exógenos, es necesario que los errores sean normales e iid para que el estimador de MCO de $b$ sea consistente. Explique si esta afirmación es cierta o falsa y por qué.

a. [10 puntos] Considere el problema de explicar el gasto de los hogares en automóviles usando una serie de características $X_i$. Muchos hogares tendrán gasto en autmóviles igual a cero. Explique las similitudes y diferencias entre el estimador tobit para muestras censuradas y el estimador de dos etapas de Heckman aplicado a dicho problema.

# Pregunta 3

Considere los datos en el archivo *ingresos_iv.csv*, usados en la tarea 2. De acuerdo con Card (1995), una variable que indique si los individuos vivían cerca de una universidad cuando eran niños, **nearc4**, puede ser empleada como instrumento de la educación en una regresión de retornos a la educación. 

a. [5 puntos] Suponga que, por alguna razón, solo tiene acceso a una variable **nearc2**, que indica si el individuo vivía cerca de una universidad que tiene solo carreras técnicas y/o educación para el trabajo. En Estados Unidos esto se conoce como *two-year colllege* o universidad de dos años. Estime el mismo modelo de variables instrumentales que en la tarea 2 para explicar el logaritmo del salario (**lwage**) en función de la educación **educ** y los siguientes controles: **exper**, **expersq**, **black**, **south**, **smsa**, **reg661**, **reg662**, **reg663**, **reg664**, **reg665**, **reg666**, **reg667**, **reg668** y **smsa66**, tratando a la educación como endógena, y usando **nearc2** como instrumento.

a. [5 puntos] ¿Qué condiciones debe cumplir **nearc2** para ser un instrumento? ¿Cuáles considera que son posibles violaciones a estas condiciones?

a. [5 puntos] Interprete el coeficiente asociado a la educación en la ecuación estructural.

a. [5 puntos] Estime la primera etapa e interprete el coeficiente asociado a **nearc2**.

a. [5 puntos] ¿Qué puede concluir respecto a la validez de la primera etapa?

a. [5 puntos] ¿Qué concluye respecto a la estrategia alternativa de usar **nearc2** como instrumento de la educación para identificar el efecto causal de la educación sobre los ingresos?

# Pregunta 4

Considere los mismos datos que en la pregunta 3, pero ahora olvidemos por un rato el problema de identificar el rendimiento de la educación. Considere un modelo de probabilidad no lineal por medio del cual queremos conocer la probabilidad de que un individuo esté en el grupo con un log del salario mayor al 80% de todos los individuos en la muestra (esto es, que pertence al 20% de los individuos con mayor log del salario). Note que esta variable no está en el archivo, debe construirla. Supongamos además que solo se observan las características **black** y **south**, así como un test de habilidad **kww**. Usaremos un modelo logit para estimar esta relación.

a. [5 puntos] Estime el modelo logit de la probabilidad de estar en el grupo del 20% de individuos con mayor log del salario, en función de **black**, **south**, **kww** y una constante.

a. [5 puntos] ¿Cómo se interpreta el coeficiente asociado a **kww**?

a. [5 puntos] ¿Cómo cambia el riesgo relativo cuando el test de habilidad **kww** se incrementa en una unidad?

a. [5 puntos] Explique cómo estimaría el error estándar del cambio en el riesgo relativo cuando **kww** se incrementa en una unidad. No es necesario que realice dicha estimación.